### ISSUE TITLE
RuntimeError: invalid device function in train.py

### ISSUE THREAD

**Issue by HyungSik-Jo** [gnina/scripts#45]
I built a new image with the most recently uploaded dockerfile . ( ubuntu18.04 - cuda11.4 - cudnn8

After adding gnina/caffe/python to the PythonPATH, it was confirmed that the caffe installation was successful.

I deleted the ligcache/reccache part to use default2017 among models/crossdocked_paper model.

command : 
python3 train.py -m ../models/crossdocked_paper/default2017_modify.model -p ../models/data/PDBBind2016/General_types/gen_uff_ -d ../data/

However, an error occurs when training existing data using train.py .
 
error :
I0622 06:02:44.843400  8979 solver.cpp:57] Solver scaffolding done.
I0622 06:02:44.858086  8979 solver.cpp:352] Iteration 0, Testing net (#0)
I0622 06:02:44.858325  8979 solver.cpp:352] Iteration 0, Testing net (#1)
Traceback (most recent call last):
  File "train.py", line 932, in <module>
    results = train_and_test_model(args, train_test_files[i], outname, cont)
  File "train.py", line 499, in train_and_test_model
    solver.step(test_interval)
RuntimeError: invalid device function

Can you tell me the cause?

**Comment by HyungSik-Jo** [comment]
This was a simple problem.
 
In the gnina CMakeList.txt file, cuda was designated as 9.0, and it was applied after changing to 11.4.

If you want to distribute the ubuntu18.04 - cuda 11.4 - cudnn 8 version from the dockfile, it would be better to edit the CMakeList.txt file.

**Comment by dkoes** [comment]
Although it could be clearer in the cmake documentation,
`find_package(CUDA 9.0 REQUIRED)`
is requiring a minimum version of 9.0, not an exact version.  The Dockerfile builds just fine for me, so I'm not sure what is going on with your setup.
