### ISSUE TITLE
questions about generate_unique_lig_poses.py

### ISSUE THREAD

**Issue by JonasLi-19** [gnina/scripts#49]
>  generate_unique_lig_poses.py - Script for counter-example generation which computes all of the unique ligand poses in a directory

Is the counter-example mean a decoy ligand pose during Cross-dock? 
Can I use this script to generate ligand-poses as MC sampling does?

**Comment by dkoes** [comment]
There is an informative comment at the top of this script.  This is *part* of the counter example generation process where we filter poses to be distinctive.
