### ISSUE TITLE
error when running train.py 

### ISSUE THREAD

**Issue by croshong** [gnina/scripts#52]
Hi 
I tried to run train.py with my data set 
following errors occcured

F0830 00:47:20.333189 25394 molgrid_data_layer.cpp:600] Check failed: pose < ex.sets.size()-1 (0 vs. 0) Incorrect pose index

I use the following command line
python train.py -m hires_pose.model -p total1_ -d types -o total1_hires_pos

dataset is total1_train0.types, total1_test0.types and gninatype file is in types folder

What could be the reason for this kind of error

**Comment by dkoes** [comment]
You haven't provided your input files, but I'm guessing you haven't specified a ligand structure?

**Comment by croshong** [comment]
Yes I found one ligand gninatype file is missing in my input data, Thanks for your  reply
