### ISSUE TITLE
How to create ligand UFF optimized and minimized poses ?

### ISSUE THREAD

**Issue by gaoshan2006** [gnina/scripts#53]
I see there are XXX_ligand.sdf , XXX_min.sdf  and XXX_uff.sdf files for most of ligands in PDBbind2016 dataset.  ( However there are still a few of ligands without _min.sdf and _uff.sdf.  )  ,   I also notice  "_these crystal ligands were
optimized independently of the receptor using the UFF forcefield of RDKit to replicate the conformer generation
process and then minimized with respect to the receptor using smina_." in the paper "Visualizing Convolutional Neural Network Protein-Ligand Scoring".  So I guess the uff.sdf is created by UFF forcefield of RDKit, then it is used for minimization.  But I am eager to know how to create uff.sdf by rdkit when adding a new crystal data .  I tried for some code like
          AllChem.EmbedMolecule(mol)
          AllChem.UFFOptimizeMolecule(mol),    or   UFFOptimizeMoleculeConfs()
But the result I got is quite different with the PDBbind2016 dataset. Could you instruct me for some steps to create the UFF posed and minized poses, please ?  Thanks a lot !

**Comment by gaoshan2006** [comment]
> 

I was just aware of except for my rdkit code, maybe the version of the rdkit I am using is different with yours. My rdkit is 2022.03.4.  One of the obvious ligand cases is “2i03/2i03_ligand.sdf”,  for which I cannot calculate the UFF optimize pose by my rdkit code -- Becase Chem.MolFromMolFile('./2i03/2i03_ligand.sdf') failed !   But it looks you could create UFF optimize pose in the PDBbind2016 dataset.

**Comment by dkoes** [comment]
https://github.com/dkoes/rdkit-scripts/blob/master/uffminimize.py

But you are right, different versions of RDKit will give different results.

**Comment by gaoshan2006** [comment]
Hi Dkoes, Many thanks !  In addition,  I'd like to make sure my understanding is right:   1) First using uffminimize.py to create ABC_uff.sdf,   2) Then from the  ABC_uff.sdf ,   the  ABC_min.sdf is created by  "smina  -l ABC_uff.sdf -r ABC_pocket.pdb --minimize -o ABC_min.sdf" , right ?

**Comment by dkoes** [comment]
yes

**Comment by gaoshan2006** [comment]
thanks, and close it
