### ISSUE TITLE
No caffe

### ISSUE THREAD

**Issue by Kerro-junior** [gnina/scripts#55]
```
Traceback (most recent call last):
  File "/home/gnina_train/train.py", line 11, in <module>
    import caffe
```

According to the README, when I built `gnina` from source, the `caffe` should already build in my `python3`. But now it is missing? What should I do?

**Comment by dkoes** [comment]
You need to add the install location of caffe to your PYTHONPATH.  It is probably in `/usr/local/python/`

**Comment by Kerro-junior** [comment]
Thanks for reply BUT new problem arises: `Couldn't build proto file into descriptor pool: duplicate file name caffe/proto/caffe.proto`

**Comment by Kerro-junior** [comment]
In addition, I am not sure if I have set the ~/.bashrc right, because I have no idea where is `install location of caffe to PYTHONPATH`

This is my gnina installation procedure: 
`apt-get install build-essential cmake git wget ......`
`cd gnina; mkdir build; cd build; cmake -DCUDA_ARCH_NAME=All ..;  make;  make install`
