### ISSUE TITLE
TypeError: Couldn't build proto file into descriptor pool

### ISSUE THREAD

**Issue by Dadiao-shuai** [gnina/scripts#56]
```
TypeError: Couldn't build proto file into descriptor pool
```

How can I fix this problem?

**Comment by Dadiao-shuai** [comment]
### For more system information you may want to know:

There is only one $PYTHONPATH: `/usr/local/python`

root@a44095df22bb:~/data/gnina_train# ls /usr/local/python/caffe
```
__init__.py  _caffe.so	    coord_map.py  draw.py   io.py	 proto
__pycache__  classifier.py  detector.py   imagenet  net_spec.py  pycaffe.py
```

### THE protobuf version
` protobuf            4.24.3`

I heard that Google Protobuf 3.8.0 can be incompatible with Caffe1.0
Or should make sure that all protocol files are up-to-date when gnina compile Caffe

**Comment by dkoes** [comment]
Yes, I'm pretty sure this error happens with the new protobuf - you need to downgrade.

**Comment by Dadiao-shuai** [comment]
I downgrade the protobuf into `3.1.0`, but it raises another error:

```
Failed to include caffe_pb2, things might go wrong!
Traceback (most recent call last):
  File "/root/data/gnina_train/train.py", line 11, in <module>
    import caffe
  File "/usr/local/python/caffe/__init__.py", line 4, in <module>
    from .proto.caffe_pb2 import TRAIN, TEST
  File "/usr/local/python/caffe/proto/caffe_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

It would be great if you group could provide every version of essential dependencies for caffe! Please~~

**Comment by dkoes** [comment]
I am using the default protobuf installed with ubuntu (through apt).  If you install the protobuf python package through pip you will run into trouble (the version is too new).  I simply don't have this installed.

**Comment by Dadiao-shuai** [comment]
> I am using the default protobuf installed with ubuntu (through apt). If you install the protobuf python package through pip you will run into trouble (the version is too new). I simply don't have this installed.

You are right, but the `gnina/script` README tell us to use pip install protobuf, it should be modified...
