### ISSUE TITLE
system has unsupported display driver / cuda driver combination

### ISSUE THREAD

**Issue by Dadiao-shuai** [gnina/scripts#57]
python3 train.py -p first_ -d /root/data --dynamic

```
  0           test first_test0.types
  0          train first_train0.types
  1           test first_test1.types
  1          train first_train1.types
  2           test first_test2.types
  2          train first_train2.types
WRITING solver.36822.prototxt

Traceback (most recent call last):
  File "/root/data/gnina_train/train.py", line 932, in <module>
    results = train_and_test_model(args, train_test_files[i], outname, cont)
  File "/root/data/gnina_train/train.py", line 441, in train_and_test_model
    solver = caffe.get_solver(solverf)
RuntimeError: system has unsupported display driver / cuda driver combination
```
### SYSTEM INFORMATION
 **nvcc --version**
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
```

` ls /usr/local`
`bin  cuda  cuda-11  cuda-11.7  etc  games  include  lib  man  python  sbin  share  src`

**Comment by Kerro-junior** [comment]
I have a suggestion, when running train.py, you may need to specific  `--gpu 0` to use the gpu in your machine?

**Comment by Dadiao-shuai** [comment]
I tried `--gpu 0`, but still : RuntimeError: system has unsupported display driver / cuda driver combination

for your imformation, I build this container with : `docker run -itd --gpus '"device=0"' ...`

**Comment by dkoes** [comment]
Sounds like a driver/cuda mismatch.  Perhaps you have updated your drivers recently and need to reboot.

**Comment by Dadiao-shuai** [comment]
**I uninstall cuda11.7 and install 11.6, and nvcc is in my path.**
please check why it still report RuntimeError when I run :

`python3 train.py -m default2018.model -p first_ -d /root/data -i 1000 --weights crossdock_default2018.caffemodel --gpu 0 --dynamic`

 ```
 0           test first_test0.types
  0          train first_train0.types
  1           test first_test1.types
  1          train first_train1.types
  2           test first_test2.types
  2          train first_train2.types
WRITING solver.2471.prototxt
Traceback (most recent call last):
  File "/root/data/gnina_train/train.py", line 932, in <module>
    results = train_and_test_model(args, train_test_files[i], outname, cont)
  File "/root/data/gnina_train/train.py", line 439, in train_and_test_model
    caffe.set_device(args.gpu)
RuntimeError: system has unsupported display driver / cuda driver combination
```

**Comment by Dadiao-shuai** [comment]
plus, is there anything to do with the model file? Do I need to modify the following:
```
        stratify_receptor: true
        stratify_affinity_min: 0
        stratify_affinity_max: 0
        stratify_affinity_step: 1.000000
```

I also deleted the line `cachefile` for receptor and ligand in the model, because I only use the default cross-val (0,1,2) types files. 

**My nvidia-smi is like:**
![image](https://github.com/gnina/scripts/assets/145245978/51f24093-d0f5-4b6f-86ec-504d79fd221b)

I believe this Driver is enough for cuda11.6

**Comment by Dadiao-shuai** [comment]
I installed this cuda11.6 from `*.deb(local)` according to the official website, and `apt-get -y install cuda`, do I need to use `pip/pip3` to install some lib for cuda in python3?

**Comment by JonasLi-19** [comment]
I'm afraid the caffe you installed when installing gnina does not properly linking to your CUDA directories(/usr/local/cuda)?

I am not an expert on caffe and cuda, but you can look the caffe/CMakelist.txt:
![image](https://github.com/gnina/scripts/assets/54503824/5cd5af45-155e-4538-bbe8-91412cd8a05e)

**Comment by Dadiao-shuai** [comment]
> I'm afraid the caffe you installed when installing gnina does not properly linking to your CUDA directories(/usr/local/cuda)?
> 
> I am not an expert on caffe and cuda, but you can look the caffe/CMakelist.txt: ![image](https://user-images.githubusercontent.com/54503824/271224046-5cd5af45-155e-4538-bbe8-91412cd8a05e.png)

I aleady add the `/usr.local/python` to PYTHONPATH, where you can find caffe.
![image](https://github.com/gnina/scripts/assets/145245978/6314e13d-e5ef-4d08-b195-8ba646b3ba7b)

I forget is there any warning information about the `caffe & cuda` when installing gnina, 
But `cmake,make,make install` all finished, and I've successfully run `gnina` to dock ligands.

I guess the problem is about `caffe`, not the Nvidia Driver, because `520.61.05` is enough for `cuda11.6/11.7`.

**Comment by dkoes** [comment]
Are you running inside docker?  Does the host system driver match the docker driver?
https://github.com/NVIDIA/nvidia-docker/issues/1256

**Comment by Dadiao-shuai** [comment]
Yes, I run gnina train.py inside docker, the nvidia driver in host system and docker are both `520.61.05`, host uses CUDA11.8, docker uses CUDA11.6.

I do not think anything wrong... Because I was told it's ok to use former cuda-toolkit in docker container, right?

**Comment by Dadiao-shuai** [comment]
FYI, I installed cuda11.7 and installed the gnina, after the error, I uninstalled cuda11.7 and installed 11.6.
Here is my cuda:
```

root@a44095df22bb:~/data/gnina_train# whereis cuda
cuda: /usr/local/cuda
root@a44095df22bb:~/data/gnina_train# which nvcc
/usr/local/cuda-11.6/bin/nvcc
```

I tried apt-get install dirmngr but this command also failed.

I also tried `apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 871920D1991BC93C   apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC` but it doesn't work out right..

**Comment by Dadiao-shuai** [comment]
Is there anything wrong about my Docker? My Docker is ` version 19.03.13, build 4484c46d9d`.

I have met `Runtime Error boost::thread_resource_error` before in `gnina/gnina:latest` image to use gnina,  and now met `system has unsupported display driver / cuda driver combination` in another docker container to use train.py.

Fed up with gpu errors!  Or should I just use cpu to do train.py?

**Comment by SanFran-Me** [comment]
@Dadiao-shuai 
### system has unsupported display driver / cuda driver combination
is this anything to do with` docker run ... -e DISPLAY=:1 ...` ?  
Or can you introduce more information of your docker container system setting like ~/.bashrc?
**Environment Variables:** You might need to set the CUDA_VISIBLE_DEVICES environment variable to indicate which GPUs Caffe is allowed to use.

**Comment by Dadiao-shuai** [comment]
I find that it is a pretty common error of `system has unsupported display driver / cuda driver combination` for docker to run gpus in many github issues.

As you mentioned, this is my `~/.bashrc`:
![image](https://github.com/gnina/scripts/assets/145245978/5418451e-4391-4f03-89fa-362b459372d2)

This is what I got in directory related to` train.py`:
![image](https://github.com/gnina/scripts/assets/145245978/96a7319e-0690-4101-b430-ad9d54d2cbce)

And this is the error report:
```
WRITING solver.2695.prototxt
Traceback (most recent call last):
  File "/root/data/gnina_iter_train/train.py", line 932, in <module>
    results = train_and_test_model(args, train_test_files[i], outname, cont)
  File "/root/data/gnina_iter_train/train.py", line 441, in train_and_test_model
    solver = caffe.get_solver(solverf)
RuntimeError: system has unsupported display driver / cuda driver combination
```

YOU MIGHT HAVE NOTICED THAT: `WRITING solver.2695.prototxt`  

@SanFran-Me

**Comment by Dadiao-shuai** [comment]
I just find the problem solver file: 
![image](https://github.com/gnina/scripts/assets/145245978/08f64391-2833-4350-b433-2b75b69ffd4a)

AND this is a part of traintrain2695.txt:
```
layer {
  name: "data"
  type: "MolGridData"
  top: "data"
  top: "label"
  top: "affinity"
  top: "rmsd_true"
  include {
    phase: TEST
  }
  molgrid_data_param {
    source: "first_iter_train0.types"
    batch_size: 50
    dimension: 23.5
    resolution: 0.5
    shuffle: false
    balanced: false
    root_folder: "/root/data"
    recmap: "completerec"
    ligmap: "completelig"
    has_affinity: true
    has_rmsd: true
  }
}
layer {
  name: "data"
  type: "MolGridData"
  top: "data"
  top: "label"
  top: "affinity"
  top: "rmsd_true"
  include {
    phase: TRAIN
  }
  molgrid_data_param {
    source: "first_iter_train0.types"
    batch_size: 50
    dimension: 23.5
    resolution: 0.5
    shuffle: true
    balanced: true
    root_folder: "/root/data"
    random_rotation: true
    random_translate: 6.0
    recmap: "completerec"
    ligmap: "completelig"
    has_affinity: true
    has_rmsd: true
    stratify_receptor: true
    stratify_affinity_min: 0.0
    stratify_affinity_max: 0.0
    stratify_affinity_step: 1.0
    jitter: 0.0
  }
}
```

Additionally, this is my types file example:
```
1 6.22 0 pdb2019_refi_train_gninatypes/3acl/3acl_rec.gninatypes pdb2019_refi_train_gninatypes/3acl/3acl_ligand.gninatypes
1 6.0096 0.5408 pdb2019_refi_train_gninatypes/4djw/4djw_rec.gninatypes first_pdbbind_v2019_docked_gninatypes/4djw_docked_0.gninatypes
0 0.6729999999999999 7.694 pdb2019_refi_train_gninatypes/4gzw/4gzw_rec.gninatypes first_pdbbind_v2019_docked_gninatypes/4gzw_docked_6.gninatypes
```

**Comment by dkoes** [comment]
Update your docker image to match your host.
