### ISSUE TITLE
--allfolds KeyError

### ISSUE THREAD

**Issue by SanFran-Me** [gnina/scripts#60]
when I use `--allfolds` flag

```
KeyError: 'train'
```

**Comment by Dadiao-shuai** [comment]
I also encountered this error when I use --allfolds to train on a single types file 'train_all.types' with 
`python3 train.py -m default2018.model --allfolds -p train_all -d /root/gnina_docker --weights crossdock_default2018.caffemodel --dynamic`

```
  File "train.py", line 479, in train_and_test_model
    idx = test_idxs[key]
KeyError: 'train'
```

**Comment by dkoes** [comment]
You can skip the case where the key isn't in test_idxs.  This is happening because the train and test set are the same so the train set isn't put in test_idxs.

`if key not in test_idxs: continue`

**Comment by JonasLi-19** [comment]
Hello professor, it might still need some other codes modified when running `--allfolds` option:


```
Iteration 1000
Train time: 208.816554
Traceback (most recent call last):
  File "train.py", line 934, in <module>
    results = train_and_test_model(args, train_test_files[i], outname, cont)
  File "train.py", line 541, in train_and_test_model
    test_net, n_tests = test_nets[key]
KeyError: 'train'
```

**Comment by JonasLi-19** [comment]
--allfolds still causes error:
```

Iteration 1000
Train time: 208.816554
Traceback (most recent call last):
  File "train.py", line 934, in <module>
    results = train_and_test_model(args, train_test_files[i], outname, cont)
  File "train.py", line 541, in train_and_test_model
    test_net, n_tests = test_nets[key]
KeyError: 'train'
```


**so can I directly add : if key not in test_idxs: continue** 

```
        #evaluate train set
        start = time.time()
        if use_reduced and (not last_test or args.skip_full):
            key = 'reduced_train'
        else:
            key = 'train'
        test_net, n_tests = test_nets[key]
        freemem()
```

**Comment by JonasLi-19** [comment]
I tried directly add : if key not in test_idxs: continue

```
        #evaluate train set
        start = time.time()
        if use_reduced and (not last_test or args.skip_full):
            key = 'reduced_train'
        else:
            key = 'train'
        test_net, n_tests = test_nets[key]
        freemem()
```

it avoid the error.

But I find the result `.out` file cannot be generated! #62

**Comment by Dadiao-shuai** [comment]
even I follow the modifications, I find` --allfolds` cannot generate `.out `files, too! @JonasLi-19 

> You can skip the case where the key isn't in test_idxs. This is happening because the train and test set are the same so the train set isn't put in test_idxs.
> 
> `if key not in test_idxs: continue`
