### ISSUE TITLE
eval model

### ISSUE THREAD

**Issue by Dadiao-shuai** [gnina/scripts#61]
if I want to evaluate the trained caffemodel, I should use train.py `--test_only`?

**Comment by dkoes** [comment]
The easiest way to evaluate a model is to use gnina to directly evaluate structures.

**Comment by JonasLi-19** [comment]
excuse me, how to **directly evaluate the structures** of a dataset, I didn't find an option in `gnina/gnina`. Is this function in `gnina/script`?

**Comment by dkoes** [comment]
Run gnina in score_only mode:
`gnina -r rec.pdb -l lig.sdf --score_only`
You can use `--cnn` to specify a built-in model or `--cnn_model` and `--cnn_weights` to specify a custom model.
